### ISSUE TITLE
startup.janet stopped working

### ISSUE THREAD

**Issue by turbohz** [CFiggers/janet-lsp#21]
It seems that 678b1a5 clears the initialization done in `startup.janet`, or something like that.

**Comment by CFiggers** [comment]
It seems you are correct—thanks for the report! I should be able to fix this shortly.

**Comment by CFiggers** [comment]
2bc9f6b is an attempt at fixing this issue—it seems to work on my end, let me know if that's working better for you as well.

**Comment by turbohz** [comment]
@CFiggers Works for me now, thanks!
