### ISSUE TITLE
Neovim: Diagnostics are not cleared when none remain

### ISSUE THREAD

**Issue by smutch** [CFiggers/janet-lsp#22]
First off - thanks for putting this LSP out there. It has been great for me whilst learning Janet.

One thing that cropped up while using the LSP in Neovim is that the last remaining diagnostic is never cleared, even once the corresponding error is fixed. It looks to be due to the the `noresponse` sent in `on-document-change` if there are no diagnostics. I removed that check and it seems to fix the problem for me:

https://github.com/CFiggers/janet-lsp/commit/02dcae2c3893846b774c3e94d55f3ebbff1b8ec5

I'm not sure if this would have any knock on effects (e.g. for other editors) but happy to PR the change if not.

**Comment by smutch** [comment]
Ha! Great!

I'm not bothered about the credit - especially since you have already made the fix. :) Very happy for you to push.

Thanks again!

**Comment by CFiggers** [comment]
Addressed with #23 . Thanks!
