### ISSUE TITLE
Import/use only failing in vscode with encoded path

### ISSUE THREAD

**Issue by strangepete** [CFiggers/janet-lsp#31]
In vscode on Windows 10, I keep seeing errors when trying to use or import a local built module. Specifically I have a jpm test script that uses the built module `../build/i2c` which is relative to where the script is executed when tested; this works fine from the cmd line, as does importing the module when installed globally. Within the editor I get the following error on use:

```
could not find module ../build/i2c:
    c%3A/Users/pete/Desktop/code/libmpsse/build/i2c.jimage
    c%3A/Users/pete/Desktop/code/libmpsse/build/i2c.janet
    c%3A/Users/pete/Desktop/code/libmpsse/build/i2c/init.janet
    c%3A/Users/pete/Desktop/code/libmpsse/build/i2c.dll
    build/i2c.janet
    build/i2c.janet
    build/i2c.janet
    ../build/i2c.janet
```

The `i2c.dll` does exist in that directory ~~but obviously the encoded colon %3a is the issue.~~ Any use of the `./` or `../` in the import name uses this path encoding, but if I enter a fake global module the error returned uses a normal `C:/Users/...` form. 

To make things weird, it seems that maybe it has to do with the dll extension. While making this issue I was playing around and made a dummy mymod.janet and moved it around, and it imported fine from the test script despite being called like `../build/mymod`.

I managed to get the LSP console working and the initial rpc from vscode returns this encoding in the `rootUri` field, which I'm assuming is being picked up, but now I'm not sure if thats part of the problem.

```
{"jsonrpc":"2.0",
"id":0,
"method":"initialize",
"params":{"processId":9720,
"clientInfo":{"name":"Visual Studio Code","version":"1.95.3"},
"locale":"en",
"rootPath":"c:\\Users\\pete\\Desktop\\code\\libmpsse",
"rootUri":"file:///c%3A/Users/pete/Desktop/code/libmpsse"
```

A little stumped! To be clear, the same dll when installed by jpm does in work on the command line, test script, as well as within vscode importing all the funcs and docstrings properly.

**Comment by CFiggers** [comment]
Hey there. :) Glad you're enjoying Janet LSP.

I'm getting some weirdness too. From VS Code:

![image](https://github.com/user-attachments/assets/9e37d755-1fd3-481f-b084-cf94a8be8eaa)

 That's running in Windows 11. Whereas in Neovim, also in Windows 11:

![image](https://github.com/user-attachments/assets/7894472e-5960-46c1-854b-68517bb308f2)

And in VS Code running in Windows 11, but talking to a Janet LSP instance running inside of WSL (Ubuntu 24.04):

![image](https://github.com/user-attachments/assets/69d43e2c-7481-46db-9a00-7e909774c13b)

They're all three using identical versions of Janet LSP (the current master, 568f434), from the same project directory (the current master of [janet-lang/spork](https://github.com/janet-lang/spork). Also, I'm using the same version of VS Code as you, 1.95.3.

Gotta say, I am confused... Seems like something different is happening when Janet LSP is launched _specifically by VS Code in Windows_...?

**Comment by strangepete** [comment]
Hello again! Actually I'm loving it -- I have the memory of a goldfish, I'm new to Janet, and new to Windows development, so this is a godsend.

I created a new c module via jpm, removed the mod/init.janet boilerplate that isn't needed, and attached the output from the lsp when restarted, definitely a lot of `%3A`... Colons should be uri safe; perhaps this is a janet++, or even a vscode issue, or a json encoding?

[lsp-log.txt](https://github.com/user-attachments/files/18048537/lsp-log.txt)

For completeness, I gathered sets of environment vars as-seen from: vscode Terminal, Windows Dev prompt, and a running Janet-LSP; nothing stands out after a few glances.
[envs-janetlsp-vscode.txt](https://github.com/user-attachments/files/18048768/envs-janetlsp-vscode.txt)
[envs-vscode-terminal.txt](https://github.com/user-attachments/files/18048769/envs-vscode-terminal.txt)
[envs-x64-dev-console.txt](https://github.com/user-attachments/files/18048770/envs-x64-dev-console.txt)

**Comment by CFiggers** [comment]
I'm thinking your intuition is probably right, that Janet LSP doesn't handle the URI-encoded colon correctly. If Neovim's client uses an unencoded colon or a relative path to communicate the project root then that would be why Neovim in Windows isn't having a problem. And obviously when run in a Linux file system there's no colon anyway.

Probably in the `initialize` and `textDocument/didOpen` functions we would want to decode the URI before storing it for later retrieval. I'll experiment with this and report back.

**Comment by CFiggers** [comment]
I think that did the trick!

![image](https://github.com/user-attachments/assets/cfc18e46-5ca5-44ba-937c-619b91ab0cd9)

This just needs a bit more polish and then I'll push it to master. Thanks for pointing this out!

**Comment by strangepete** [comment]
Oh awesome! I was just about to share that I saw this comment on the vscode api site about Uri.toString aggressively encoding, and even mentions the %3A conversion -- https://code.visualstudio.com/api/references/vscode-api#Uri.toString

**Comment by strangepete** [comment]
Yesss #32 fixes this, thank you! PEGs are great

**Comment by CFiggers** [comment]
My pleasure. 🙂 My plan is to push out an updated version of Janet++ soon as well, to include these improvements in the extension (plus some other housekeeping for the 1.37.1 release of Janet).

**Comment by CFiggers** [comment]
Janet++ v1.1.7 is available now as a pre-release in VS Code if you want to give it a try. 😊 Thanks again for the bug report!

**Comment by strangepete** [comment]
I've been trying it for a little bit, so far no issues seen on Windows 10 locally, or using vscode remote ssh to an ubuntu box (extension running remotely) with a separate project. The tell a joke feature also works on both btw 😂

Red squiggles begone! Thank you, I'm just glad it wasn't a PEBKAC

**Comment by strangepete** [comment]
Hey @CFiggers, I'm not going to reopen this, but another possibly related error started popping up out of the blue, maybe you can help me narrow it down. I am pretty sure the only thing that has changed was a vscode update and/or reboot...

The fix before definitely was working properly (though I just noticed your PEG is missing a %20 space match; yay Windows) so it was a little surprising.

```
could not find module ../build/cfuntest-native:
    ../../c:/Users/pete/Desktop/code/cfuntest/build/cfuntest-native.jimage
    ../../c:/Users/pete/Desktop/code/cfuntest/build/cfuntest-native.janet
    ../../c:/Users/pete/Desktop/code/cfuntest/build/cfuntest-native/init.janet
    ../../c:/Users/pete/Desktop/code/cfuntest/build/cfuntest-native.dll
    build/cfuntest-native.janet
```

When adding ./ or ../ the local directory suddenly prepends a `../../`

The LSP debug looks fine for all the early env stuff and rootUri, but the first I see the ../../ is here in the output on a clean test project:

```
server:18:> [INFO:core] handle-message received method request: `textDocument/didOpen`
server:19:> [INFO:evaluation] `eval-buffer` received filename: `../../c:/Users/pete/Desktop/code/cfuntest/project.janet`server:20:> [INFO:evaluation] `eval-buffer` received str: `(declare-project
  :name "cfuntest"
  :description ``` ```
  :version "0.0.0")

(declare-native
  :name "cfuntest-native"
  :source @["c/module.c"])`
server:21:> [INFO:evaluation] `eval-buffer` is returning: @[]
server:22:> [INFO:evaluation] `eval-buffer` returned: @[]
server:23:> [INFO:evaluation] `run-diagnostics` is returning these errors: @[]
server:24:> [INFO:evaluation] `run-diagnostics` is returning this eval-context: @{:current-file "../../c:/Users/pete/Desktop/code/cfuntest/project.janet"}
```

Tested with Janet 1.36 & 1.37.1 with both prerelease and previous Janet++, which is also why I'm really confused.

**Comment by strangepete** [comment]
Hm, I got the error to go away, but I can't figure out what changed. Removing the `..` from `(use /build/libmpsse)` _now_ works both in vscode and via jpm test. I suspect something changed on the vscode workspace settings, but it happens in multiple projects. I tried rolling back to 1.95.3, but have not yet tried with a full, clean install.

Since I can't provide actual repro steps, I'll leave this closed, but if there is anything you can think of that I can check or poke around, I'd be happy to keep investigating. Thanks for all your help
