### ISSUE TITLE
Better Sandboxing of User Code

### ISSUE THREAD

**Issue by CFiggers** [CFiggers/janet-lsp#8]
Presently, Janet LSP flychecks the user's code as received from the LSP client in the same environment that the server itself is running in. This creates opportunities for symbol collision and other glitchy behavior. 

A better architecture would have user code evaluated in a separate environment table—either by specially-constructing an environment table in `eval.janet` to be passed to `eval-buffer` and its `run-context` call, or by running the functions in `eval.janet` in a totally separate fiber from the server process itself.

More testing and experimentation needed here.

**Comment by CFiggers** [comment]
Delivered with 25e5274

**Comment by sogaiu** [comment]
On a side note, IIUC, part of flycheck's design incorporates a kind of stance on security [1].

I guess these days in VSCode one is asked about whether one trusts the authors of whichever project one is "opening" for the first time, so may be one can consider that a user has been suitably warned?

A not-so-obvious bit might be that code for dependencies (including transitive ones) might also run.

---

[1] Probably known, but for reference, I'm referring to the docstrings of [`no-side-effects`](https://github.com/janet-lang/janet/blob/9142f38cbceb72e7d2d8a12846d2c22c2322fc34/src/boot/boot.janet#L3863-L3864) and [`flycheck-evaluator`](https://github.com/janet-lang/janet/blob/9142f38cbceb72e7d2d8a12846d2c22c2322fc34/src/boot/boot.janet#L3888-L3890) (and ofc the code itself).

**Comment by CFiggers** [comment]
Module security is definitely an open question for me in Janet as a whole.

> A not-so-obvious bit might be that code for dependencies (including transitive ones) might also run.

You're right, that isn't so obvious, but it's definitely the case, and not just where this LSP is concerned. 

Janet, the language, allows arbitrary code execution during module import, and some libraries depend on that to correctly export their symbols. This became apparent to me in the process of diagnosing some very frustrating bugs with the version of the LSP that is shipping in Janet++ v1.1.0. 

`spork/path` is an example—at compile time, `spork/path` dynamically redefines some of its own symbols based on the running operating system. In Janet++ v1 1.0 and prior, Janet LSP only flychecked that mutating code at the end of `spork/path` and would therefore only have 2/3 the symbols available. This caused the LSP to throw diagnostic errors even when actually running the exact same code using `janet foo.janet` executed just fine. `ianthehenry/cmd` is another example. For both of these libraries, the module's code must be fully executed or else the import is not complete.

The reality is, Janet itself does not give protections or guarantees around code execution by imported modules during import. At least at time of writing, Janet's module/library security story boils down to "go read and understand the source before you run the code." Which, to be fair, is not worse than C. And Janet code is at least, subjectively, much easier to read than C code, from my perspective at least (that doesn't help much with native modules, of course).

I don't think this LSP project will be able to have *much* stronger security promises than the language itself does—but maybe we can make the risk a bit more explicit. Perhaps I can, as you suggest, present a warning to the user and maybe save a whitelist of "ok to run" modules in the project somewhere (it is conventional for LSPs to store state like that in a .lsp folder in the project root). That wouldn't do anything to protect the user when they actually go to run their project anywhere, but it might prevent the LSP itself from firing missiles that shouldn't be fired. 

I'll have to think about where to locate that logic (in the LSP itself vs in the Janet++ VS Code extension). I don't think there's a perfect way to handle that across different editors, which Janet LSP aspires to support.

**Comment by sogaiu** [comment]
Thanks for your thoughts.  Still digesting them.

I did go in search of other LSP implementations (and related things) for some lisp-likes.  Was thinking perhaps some of them might have faced similar issues.  Here are some I found:

* [cl-lsp](https://github.com/cxxxr/cl-lsp) - an LSP for Common Lisp.  Looks kind of inactive and didn't figure much out from the README.
* [scheme-lsp-server](https://codeberg.org/rgherdt/scheme-lsp-server) - seems like it is kind of a collection where some of the supported Scheme's include Chicken, Gambit, and Guile.  I got the sense that implementations differ in parts via [this](https://codeberg.org/rgherdt/scheme-lsp-server#a-name-user-content-specific-implementations-a-notes-to-specific-implementations) -- e.g. for Chicken - "The implementation for "jump to definition" is for now quite limited. I wrote a ctags-inspired code for CHICKEN that scans the project files for definitions." 
* [Magic Racket VSCode Extension](https://github.com/Eugleo/magic-racket)
* [racket-langserver](https://github.com/jeapostrophe/racket-langserver) - used by Magic Racket.  Seems to talk to [DrRacket](https://github.com/racket/drracket) which apparently has an API that exposes some useful functionality
* [clojure-lsp](https://github.com/clojure-lsp/clojure-lsp) - at some point I think this only used static analysis (so no code evaluation) via clj-kondo (not sure if that's still true)
* [fennel-ls](https://git.sr.ht/~xerool/fennel-ls) - apparently static analysis only

On the whole my impression is that evaluation is being avoided, but I'm not so sure yet.
